### ISSUE TITLE
The link to download pretrained models is not working 

### ISSUE THREAD

**Issue by abhisheksgumadi** [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#13]
Hello

  I tried to access the link - https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/blob/master/bit.ly/drive-s3prl but it is not accessible. 

Can you please clarify which link do we need to access for the pretrained model?

Thanks

**Comment by andi611** [comment]
The link in [README.md](https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/blob/master/README.md) has been updated, it should be: [http://www.bit.ly/drive-S3PRL](http://www.bit.ly/drive-S3PRL).
