### ISSUE TITLE
Why reconstruct linear spectrogram?

### ISSUE THREAD

**Issue by iamjack2018** [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#15]
Thanks for such a good work! I have a specific question about the reconstruction goal. I am wondering, in both Audio ALBERT and Mockingjay large, why you decided to reconstruct the corresponding linear spectrogram instead of the input 160-dimension mel spectrogram? Do you have any statistics for how much performance gain we can get by reconstructing linear spectrogram instead of input mel spectrogram?

Thank you so much

**Comment by andi611** [comment]
The initial thought is, we hope that the model can capture more information through reconstructing a more frontend acoustic representation.
However, in our later experiments, we find that `Mel->Mel` and `Mel->Linear` yield similar performance for phone classification.
So I would say `Mel->Mel` is sufficient (The Mockingjay BASE is `Mel->Mel` and it also performs well).
I'm not one of the authors of Audio ALBERT, but I believe they simply follow the implementation of Mockingjay, and there is no particular reason for choosing such a setting.

**Comment by iamjack2018** [comment]
That makes sense. Thank you for your clarification.
