### ISSUE TITLE
Fine tune Mockingjay LARGE

### ISSUE THREAD

**Issue by iamjack2018** [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#16]
Mockingjay paper says "We did not fine-tune the LARGE model, as it is meant for extracting representations." Does it mean Mockingjay LARGE will have worse performance after we fine tune it?

**Comment by andi611** [comment]
No, LARGE can also be fine-tuned, and the performance gain is expected.
For example, in [Audio ALBERT](https://arxiv.org/pdf/2005.08575.pdf) LARGE is fine-tuned to improve phone classification (Figure 3b, denoted as Mockingjay-12L-FT).
