### ISSUE TITLE
why dev_set and test_set not used in pre-training 

### ISSUE THREAD

**Issue by CharlieZhaoyl** [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#18]
Hi, I notice that the code only uses train_set during the pre-training progress. Could you plz explain why dev-test and test-set are not used? Thanks!

**Comment by andi611** [comment]
I'm not certain of your question. 
dev and test are not supposed to be used during training, the reason is in real circumstances (for example a product), you won't have access to inference data.

**Comment by CharlieZhaoyl** [comment]
Yes, you are right. Thanks for the explanation, I found myself misunderstand the pre-training progress of BERT-like model
