### ISSUE TITLE
Does the simple network structure design of downstream task affect the results ?

### ISSUE THREAD

**Issue by wotulong** [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#19]
Thanks for you job. I want to know does the simple network structure of downstream task affect the result? Because if you use a fine tuned network of pretrained network , it jusk like you have a more complex network than you directly feed the acoustic future input the downstream network which only have two layers. Do you have any experiment that training the network which combined ALBERT network and downstream network , and feed it with acoustic fetures from strat. Thanks.

**Comment by andi611** [comment]
> Do you have any experiment that training the network which combined ALBERT network and downstream network , and feed it with acoustic fetures from strat.

I supposed you mean training the "Transformers (e.g. AALBERT) + downstream model" from _scratch_.
Yes, I have experimental results that show _pre-training + finetuning_ yields better performance than _scratch_.

To be more specific, for phone classification and ASR, _pre-training + finetuning_ constantly outperforms _scratch_.
On the other hand, _pre-training + finetuning_ and _scratch_ both fail for speaker recognition. This proves that good results are not contributed by complex networks.
The paper that contains these experiments will be available online soon.

**Comment by wotulong** [comment]
> > Do you have any experiment that training the network which combined ALBERT network and downstream network , and feed it with acoustic fetures from strat.
> 
> I supposed you mean training the "Transformers (e.g. AALBERT) + downstream model" from _scratch_.
> Yes, I have experimental results that show _pre-training + finetuning_ yields better performance than _scratch_.
> 
> To be more specific, for phone classification and ASR, _pre-training + finetuning_ constantly outperforms _scratch_.
> On the other hand, _pre-training + finetuning_ and _scratch_ both fail for speaker recognition. This proves that good results are not contributed by complex networks.
> The paper that contains these experiments will be available online soon.

Thanks for your reply, looking forword to your next paper.Does ALLBERT or MOCKINGJAY could achieve the same performance as other SOTA method in some SLP task with same training data, it will helpful. Thanks a lot.

**Comment by andi611** [comment]
> Does ALLBERT or MOCKINGJAY could achieve the same performance as other SOTA method in some SLP task with same training data, it will helpful.

Could you please elaborate on which SOTAs you wish we compare with.

**Comment by wotulong** [comment]
> > Does ALLBERT or MOCKINGJAY could achieve the same performance as other SOTA method in some SLP task with same training data, it will helpful.
> 
> Could you please elaborate on which SOTAs you wish we compare with.

For speaker speaker recognition, as I konw, Shaojin Ding's paper "AutoSpeech: Neural Architecture Search for Speaker Recognition" show that they get the SOTA performance. And for phoneme identification, may be the RNN-T based model, like "Two-Pass End-to-End Speech Recognition", but it's design for ASR task.

**Comment by andi611** [comment]
> 
> For speaker speaker recognition, as I konw, Shaojin Ding's paper "AutoSpeech: Neural Architecture Search for Speaker Recognition" show that they get the SOTA performance. And for phoneme identification, may be the RNN-T based model, like "Two-Pass End-to-End Speech Recognition", but it's design for ASR task.

Thanks for your information! We will try to consider these papers in our future work!

**Comment by wotulong** [comment]
> > For speaker speaker recognition, as I konw, Shaojin Ding's paper "AutoSpeech: Neural Architecture Search for Speaker Recognition" show that they get the SOTA performance. And for phoneme identification, may be the RNN-T based model, like "Two-Pass End-to-End Speech Recognition", but it's design for ASR task.
> 
> Thanks for your information! We will try to consider these papers in our future work!

Thanks.
