### ISSUE TITLE
How to implement masking segments along channel axis

### ISSUE THREAD

**Issue by CharlieZhaoyl** [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#21]
Hi Andy, 
I really like your new paper!
When reading the code and paper TERA, I have a question: how to implement masking segments along channel axis? Is it done when extracting acoustic features? I will appreciate if you could give me some information about that.
Thanks!

**Comment by andi611** [comment]
Hi,
Thanks for appreciating our work.
The frequency masking is implemented [here](https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/blob/cc486de38b5729589c21fbe0c9a3e48a6911e950/transformer/mam.py#L163-L171).
It is done _after_ feature extraction, a _dynamic_ process during training.
