### ISSUE TITLE
Pretrain an auto encoder using ALBERT 

### ISSUE THREAD

**Issue by spygaurad** [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#32]
Can i use the ALBERT model to pretrain an autoencoder?

**Comment by andi611** [comment]
> Can i use the ALBERT model to pretrain an autoencoder?
> Would it be possible using this toolkit? It seems i need to write my own decoder to pretrain encoder and decoder at the same time. Would it be possible for you to provide me with some instructions on how to do that?
>
Yes, you need to write your own decoder.

For pre-training, `run_upstream.py` [calls](https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/blob/b72a2cd9fa106d77f4011c75432eecacc927552c/run_upstream.py#L92-L116) the upstream `Runner` ([transformer/runner.py](https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/blob/b72a2cd9fa106d77f4011c75432eecacc927552c/transformer/runner.py#L31)) like so:
```python
runner = Runner(args, config, dataloader, ckpdir)
runner.set_model()
runner.train()
```
Hence if you modify the `set_model()` and `train()` function in `Runner`, you can use our implementation to train your autoencoder.
