### ISSUE TITLE
Resume an Interrupted Training

### ISSUE THREAD

**Issue by ZJY382653** [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#33]
Dear Author, I'm sorry to bother you for some simple question.
1.When i trained my own pre-training model with our dataset , I accidentally interrupted the training. And i wanted to go on training on the checkpoint model file, but i did'nt find a way to do so. 
2.Similar to question 1. When i evaluated downstream task with my own classifier on your pre-trained model--melLarge,  the program broke down sometimes for my data's big size. I can't continue on my saved ckpt file using your example code givev in README.md, though i saved the total net rather than only weights. 
My English is not good. Sorry!

**Comment by andi611** [comment]
The two questions are about how to resume an interrupted training, which we haven't implemented yet (a TODO for future). 
For now, you can find some answers [here](https://www.google.com/search?rlz=1C1GCEU_zh-TWTW917TW917&sxsrf=ALeKk010mMcS55oGd5xK2koau7je0rer2A%3A1599717992335&ei=aMJZX-7_E6ezmAXrkaCQCw&q=pytorch+resume+training+from+checkpoint&oq=resume+pytorch+training+&gs_lcp=CgZwc3ktYWIQARgCMgYIABAIEB4yBggAEAgQHjIGCAAQCBAeMgYIABAIEB46BAgjECdQ4jtY4jtgv1doAnAAeACAAVKIAYQBkgEBMpgBAKABAaoBB2d3cy13aXrAAQE&sclient=psy-ab).

To avoid accident crashes like in 2., you can reduce the number of workers in the dataloader (['dataloader']['n_jobs'] in config .yaml).

**Comment by andi611** [comment]
This function has been implemented: https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/commit/937796373bd915a15aac4290e56c3c30012d4251
Usage: `python run_upstream.py --resume=result/result_transformer/ckpt_dir_to_resume`
