### ISSUE TITLE
about the downstream evaluation

### ISSUE THREAD

**Issue by ArtemisZGL** [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#41]
Hello, I'm sorry for asking some stupid question.  
1.  I have trained a mockingjay with the melbase config. And then I want to evaluate it on downstream task. When loading the model, it shows the error below. And I can't find the config for the transformer in the downstream.yaml.
```
 "Pre-trained weights NOT loaded!".
size mismatch for input_representations.spec_transform.weight: copying a param with shape torch.Size([768, 160]) from checkpoint, the shape in current model is torch.Size([768, 1]).',))
```
  
2. Besides, I'm a little confused that where does the speaker information comes from when evaluate the speaker recognition task? And what if I pretrain in different language, do you have some suggestions for phone classification?  

Thanks a lot.

**Comment by andi611** [comment]
Hi,

for 1) in order for me to help, please provide the arguments you used when you encounter this error.
for 2) What do you mean by speaker information? do you mean the ground truth speaker label? If so, it is provided in the LibriSpeech dataset (the name of each utterance file contains the speaker ID). And No I haven't explored other languages.

Thanks

**Comment by ArtemisZGL** [comment]
@andi611 sorry for late reply. I found the error above is caused by the online feature extracting. And after using the script to extract features, I met another error while training. Here is my command and the log.
```
 python run_downstream_babel.py --run=speaker_utterance --upstream=transformer --ckpt=/data3/zgl/mock_babel_ckpt/states-500000.ckpt
```
```
File "/Self-Supervised-Speech-Pretraining-and-Representation-Learning/transformer/model.py", line 119, in forward
    input_representations = spec_transformed + pos_enc
RuntimeError: The size of tensor a (10909) must match the size of tensor b (5000) at non-singleton dimension 1
```

I think it's maybe caused by my own dataset. But all of them were extracted feature by the same script. What reasons may cause this error?

**Comment by andi611** [comment]
> ```
run_downstream_babel.py
> ```
> 
> ```
> File "/Self-Supervised-Speech-Pretraining-and-Representation-Learning/transformer/model.py", line 119, in forward
> 
>     input_representations = spec_transformed + pos_enc
> 
> RuntimeError: The size of tensor a (10909) must match the size of tensor b (5000) at non-singleton dimension 1
> ```


It seems like you've modified our original code, including `run_downstream.py` and `data_loader.py`.

Hence I can only guess that `10909` and `5000` are the sequence length of `spec_transformer` and `pos_enc` (please verify this). If so, then you have to change this line [here](https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/blob/49e51cbf610979c7ef975bd77861d3fa696c84c5/transformer/nn_transformer.py#L437).

**Comment by ArtemisZGL** [comment]
@andi611 thanks, I have just change the dataloader for librispeech to another dataset.  And the whole dataset maybe just one sample is too long for test split, maybe just the test split will not drop the too long sample which is showed in the downstream config file.

**Comment by andi611** [comment]
Yes, the test split will not drop too long sequences.
