### ISSUE TITLE
Downstream Evaluation RuntimeError: size mismatch

### ISSUE THREAD

**Issue by joram5** [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#45]
Hi Andi,

Thanks for providing this code and data.

I am trying to run downstream evaluation with pre-trained model and data from S3PRL drive.

This is the command I am running:

python run_downstream.py --run=phone_linear --upstream=transformer  ckpt=../S3PRL/mockingjay/MelMediumM9_libri/states-500000.ckpt

I am able to load the model:

[run_downstream] - getting upstream model: transformer
[Transformer] - Pre-trained weights loaded!
[Transformer] - Number of parameters: 42898176

But the downstream training fails:

[run_downstream] - Loading input data: ['train-clean-100'] from data/libri_fmllr_cmvn
[run_downstream] - Loading phone data: data/cpc_phone
[run_downstream] - getting train dataloader...
[Dataset] - Possible phone classes: 41, number of data: 20547
[run_downstream] - getting dev dataloader...
[Dataset] - Possible phone classes: 41, number of data: 2283
[run_downstream] - getting test dataloader...
[Dataset] - Possible phone classes: 41, number of data: 5708

I get the following error at the beginning of the training:

RuntimeError: size mismatch, m1: [3186 x 120], m2: [480 x 768] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:41
Iteration:   0% 0/3425 [00:14<?, ?it/s]
  0% 0/500000 [00:15<?, ?it/s]

What can be the problem?

Regards
Joram

**Comment by andi611** [comment]
The problem is caused by using the wrong data `data/libri_fmllr_cmvn` on the model `mockingjay/MelMediumM9_libri`.

To continue to use `data/libri_fmllr_cmvn`, you can simply download the models I've provided [here](https://drive.google.com/drive/folders/1bwlhRhXg8fiE38XY5GVF1ZqSWL3-TlDs?usp=sharing), and everything should work fine.

**Comment by joram5** [comment]
Hi Andi,

Thank you for your support. Your advice solves this problem.

Currently I am running the following command line (in case it will help other users):

python run_downstream.py --run=phone_linear --upstream=transformer --ckpt=../S3PRL/mockingjay/fmllrLarge960-T-libri/states-1000000.ckpt

I had a problem with torch and torchaudio versions. The requirement.txt asks for torch==1.3.0,
It seems that the current code base uses functions from a more advanced releases of torch,

I encountered the following fail when using torch==1.3.0:

import torch
print(torch.__version__)
1.3.0
import torchaudio
print(torchaudio.__version__)
0.3.1
.....
from transformer.nn_transformer import TRANSFORMER
from utility.preprocessor import OnlinePreprocessor
from torchaudio.functional import magphase, compute_deltas
...
ImportError: cannot import name 'compute_deltas'

After upgrade  to torch 1.4.0 and torchaudio 0,4,0 this problem is solved and the training is running ok (just started). 

Thank you for your great advice.

Regards
Joram

**Comment by andi611** [comment]
Hi, thank you for your constructive feedback!
I've [updated](https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/commit/9d83f757aa9454d72979e626ebf8124913b3cf5f) the `requirement.txt` according to your suggestion.

Hope you have a nice day!
Andy

**Comment by joram5** [comment]
Hi Andi

I am glad to help.
Thank you for sharing your code.
It is really great.

Regards
Joram

‫ב-27 באוק׳ 2020, בשעה 4:37, ‏‏Andy T. Liu ‏<notifications@github.com> כתב/ה:‬

﻿

Hi, thank you for your constructive feedback!
I've updated<https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/commit/9d83f757aa9454d72979e626ebf8124913b3cf5f> the requirement.txt according to your suggestion.

Hope you have a nice day!
Andy

**Comment by joram5** [comment]
Hi Andy,

There seems to be a problem accessing the S3PRL drive ( http://www.bit.ly/drive-S3PRL ).

Can you check what happened?

Regards
Joram
