### ISSUE TITLE
GoogleDrive 404

### ISSUE THREAD

**Issue by Skyy93** [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#48]
Hello, 

unfortunately the Google Drive with the Training Checkpoints isnt available anymore. Could you please reup or update the link?

Thank you very much

**Comment by andi611** [comment]
The Google Drive (G Suite) account I used to store data was disabled by Google. I'm trying to restore the account, otherwise, I will re-upload the data again to a new Google Drive within a few days.

**Comment by andi611** [comment]
@Skyy93 The Google Drive account is back online and working now.
