### ISSUE TITLE
what's the L1Loss value when pretrain model's training finished ?

### ISSUE THREAD

**Issue by apoca909** [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#53]

**Comment by andi611** [comment]
There is no exact value, it largely depends on the feature (or preprocessing setting) you used.

**Comment by apoca909** [comment]
> There is no exact value, it largely depends on the feature (or preprocessing setting) you used.

I use the default args setting in extract_feature func.

**Comment by andi611** [comment]
For fbank, it should be within the range of 0.85~0.95.
Don't worry too much about the L1Loss value.

FYI, we recommend you pre-train with our latest feature: [on-the-fly preprocessing](https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#on-the-fly-feature-extraction).
This omits data preprocessing beforehand, and the trained model will have a built-in preprocessor that can take wave as input.

**Comment by apoca909** [comment]
> For fbank, it should be within the range of 0.85~0.95.
> Don't worry too much about the L1Loss value.
> 
> FYI, we recommend you pre-train with our latest feature: [on-the-fly preprocessing](https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#on-the-fly-feature-extraction).
> This omits data preprocessing beforehand, and the trained model will have a built-in preprocessor that can take wave as input.

very much thx.
