### ISSUE TITLE
deprecated code reference

### ISSUE THREAD

**Issue by SolomidHero** [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#56]
https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/blob/61e9edff0e0b7f5266f038bb096265f2bc392ffa/run_downstream.py#L23

But dual transformer doesn't exist since commit [b7723c](https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/commit/b7723c4b269b5242ae7c9b3746e783153bfa6b46).

This lead to import and other errors

**Comment by andi611** [comment]
Hi, thanks for the heads up!
I've updated the code on master.
