### ISSUE TITLE
Training our own data with multi-GPU

### ISSUE THREAD

**Issue by 15458wew** [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#58]
Thank you for opening such good codes.

But when I use it, I can only use one GPU for model training. How can I use multiple GPUs to train a model?

**Comment by 15458wew** [comment]
How to use multiple GPUs to complete the training of downstream tasks？

**Comment by andi611** [comment]
I believe you can do it with `--multi_gpu`.
This will effect [this](https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/blob/cc97b9325028f8357e5640974b6b0e94d946c1ba/transformer/runner.py#L78-L81).

We currently don't support multi-gpu downstream training, as downstream models are small.

**Comment by 15458wew** [comment]
ok，thanks for your answer
