### ISSUE TITLE
Fail in resolving dependencies

### ISSUE THREAD

**Issue by swdanielli** [andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning#59]
As i `pip install -r requirements.txt`, I got errors 

    The user requested numpy==1.14.5
    librosa 0.7.2 depends on numpy>=1.15.0`

    The user requested numpy==1.14.5
    matplotlib 2.2.3 depends on numpy>=1.7.1
    numba 0.48.0 depends on numpy>=1.15`

I think change `numpy==1.14.5` in requirements.txt to `numpy==1.15` should fix the issue. Has anyone experienced the same problem?

**Comment by andi611** [comment]
Yes, we haven't been maintaining this file.
I've made some changes here: https://github.com/andi611/Self-Supervised-Speech-Pretraining-and-Representation-Learning/commit/d687728227a19b3564113d8146869c179e5d54a3
